### ISSUE TITLE
Issues after Installed ECS Virtual

### ISSUE THREAD

**Issue by marciakubo** [EMCECS/ECS-CommunityEdition#168]
I've installed the ECS Virtual yesterday. The installation worked with sem issues. The problem is when I try to create a Storage Pool, stays initializing forever ...

Everyone has seen this issue?

Is it possible to help?

**Comment by brokenjacobs** [comment]
I'm testing a theory on this right now but I'm fairly certain it's correct. RHEL/Centos 7.1 have a fix note about removing the sg kernel module from the default boot, and I'm fairly certain vipr depends on it (as noted from the boot.log from the docker container complaining about it). To make it load at boot, add a file called /etc/modules-load.d/sg.conf with one line in it:
sg

Here is the relevant info from rhel 7.1 release notes.
rhel 7.1:
⁠sg3_utils component, BZ#1186462
Due to the conversion of the iprutils package to use systemd instead of legacy init scripts, the sg driver is no longer loaded during system boot. Consequently, if the sg driver is not loaded, the /dev/sg* devices will not be present.
To work around this issue, manually issue modprobe sg or add it to an init script. Once the sg driver is loaded, the /dev/sg* devices will be present and the sg driver may be used to access SCSI devices.

**Comment by brokenjacobs** [comment]
FYI does not appear to resolve the problem.

**Comment by APeter0807** [comment]
Issue resolved for reporter over e-mail. May have been related to portal GUI incorrectly reporting storagepool status (issue with the image under ongoing investigation).
