### ISSUE TITLE
What is the difference between Community Edition and Business Edition?

### ISSUE THREAD

**Issue by imYerik** [EMCECS/ECS-CommunityEdition#176]
Hi guys,
What is the difference between Community Edition and Business Edition?
And is there a detailed comparison?

Thanks a lot.

**Comment by jasoncwik** [comment]
Community edition is designed for users to test the basic functionality of ECS, for example writing S3 or Swift applications or trying out the management GUI features.  The main differences between Community Edition and Software / Appliance are:
1. Reduction in memory footprint from 64GB per node to 16GB
 a. Less threads per process
 b. Less partitions per data table type (32 vs 128)
 c. Shared thread pools inside the processes instead of separate thread pools for I/O and periodic tasks.
2. Tuning of disk management parameters to preallocate less chunk so we can run with 100GB of disk (the smallest ECS appliance node has 200 _terabytes_ of storage).
3. No separate containers for Zookeeper (they run in the same container)
4. No "fabric" layer to manage containers and hardware (e.g. watch for disk failures, add/remove disks, etc)

Because of the above changes, we do not support using Community Edition for testing failures, testing performance, or use in production.  It is also not supported by EMC support (you can't open an SR).  Support is only provided best-effort here on the GitHub site.
