### ISSUE TITLE
Refactor installation process

### ISSUE THREAD

**Issue by adrianmo** [EMCECS/ECS-CommunityEdition#186]
As per @jasoncwik request, I've been looking at how to improve ECS CE installation and after reviewing the current state and the installation of other popular distributed system (e.g. [OpenStack](https://github.com/openstack/openstack-ansible), [OpenShift](https://github.com/openshift/openshift-ansible)) these are my thoughts:

- We should replace the Python scripts by a configuration management tool such as Ansible, Chef or Puppet. AFAIK, that decision was already taken in favor of Ansible, which I also think it is the best fit for our use case. Even though any other CM would also do the job, Ansible's agentless design and the lack of a custom DSL makes it the preferred option, IMHO. 

- I think we should not handle single-node installation differently. Instead, single-node installation should use the same Ansible code and scripts used for multi-node. That means that we have to create configuration and installation files in a modular, reusable way so that they can be consumed by both single-node and multi-node deployments. This will make the project easier to maintain. 

- In addition, these configuration files should also be consumed by any orchestration and deployment systems (e.g. CloudFormation, OpenStack Heat, Terraform, Vagrant) and applied to any target platform (e.g. AWS, OpenStack, Google Cloud, libvirt).

Please let me know what you think and whether somebody has started to work on this to coordinate efforts.

**Comment by brokenjacobs** [comment]
My vote goes to Ansible. Presumably a set of ansible modules for things like:
emc-ecs-user
emc-ecs-namepsace
emc-ecs-bucket... etc using the ecsminion libraries would got a long way to automating provisioning similar to the 'step2' script currently used for installation.  step1 could probably be replaced with just a standard playbook to retrieve the docker container, etc. I've gone down the path of writing ansible automation to deploy ec2 instances of the community edition using centos , which I can probably share, but for the most part it still calls the deployment scripts. They are the biggest roadblock, to the process, since they are not resumable.

**Comment by padthaitofuhot** [comment]
I agree, Ansible is the way to go.  I've a PR submitted #201 for an Ansible-based installer.  

I would also like to see Ansible modules for the various management API components, as well as vetting existing modules for Swift, S3, CAS, NFS, etc.

**Comment by padthaitofuhot** [comment]
What else should be implemented out of this?  I'm not sure how to do:
> In addition, these configuration files should also be consumed by any orchestration and deployment systems (e.g. CloudFormation, OpenStack Heat, Terraform, Vagrant) and applied to any target platform (e.g. AWS, OpenStack, Google Cloud, libvirt).

It seems like an good idea, so I'm assigning @captntuttle also to provide his research on what this looks like for AWS and GCE.  I don't know that any of us have tried deploying in OpenStack yet.

**Comment by padthaitofuhot** [comment]
@captntuttle poke

**Comment by padthaitofuhot** [comment]
Closing this in favor of new organizing efforts.
