### ISSUE TITLE
How ECS deals with  concurrent read and write

### ISSUE THREAD

**Issue by imYerik** [EMCECS/ECS-CommunityEdition#188]
Hello all,
If userA is writing an object, and userB write or read this object in same vdc site at the same time. How does ECS ensure the data consistency?

Thanks.

**Comment by jasoncwik** [comment]
For every bucket and object, there is the concept of ownership.  In a multi-VDC environment, an object will always have a site that currently owns the object (the site it was created in).  Within a site, the object table is  split into 128 partitions that are distributed across the nodes.  The partition that currently owns an object will be responsible for serializing the updates to the object metadata.  For the object data itself, ECS always operates in an append-only manner when writing the data to disk, so we never overwrite the existing data.

If a read and a write for a particular object are issued at the same time, there will be a race between the update and the read since there's no locking in ECS.

For concurrent writes to the object, we do provide some optimistic locking by using the if-match and if-none-match extensions to the S3 protocol.  If you want to ensure an object doesn't exist, you can use "if-none-match: *" on your PUT.  If you want to ensure you're overwriting a particular version of an object, you can use if-match with the Etag you expect to overwrite.  If you don't want to overwrite an object with the same data, you can use if-none-match with the MD5 of the current object contents.  If you are doing frequent updates to objects, we definitely recommend the use of if-match since we can't otherwise guarantee the order that writes will commit.

**Comment by imYerik** [comment]
Thank you Jason. It's much clearer now. 
And I have another question. For big file and small file, I know that big file will get a good bandwidth and small file will get a good TPS.  Which is more suitable for ECS?

**Comment by jasoncwik** [comment]
ECS can handle both use cases well, however with small file you will see higher latencies than traditional storage systems so it's important to use many threads to get good throughput.  For example, an 8-node ECS U3000 writing 10kB objects will get peak write throughput around 1000+ threads.  For larger objects, a smaller number of threads like 150 would be required to get peak bandwidth.

**Comment by imYerik** [comment]
It's great! Thanks Jason.  👍
