### ISSUE TITLE
Extremely stupid question

### ISSUE THREAD

**Issue by shanetreacy** [EMCECS/ECS-CommunityEdition#263]
Forgive the dumb question, but I presume it is not expected behaviour that if one node of a 4 node ECS CE cluster goes down that the whole cluster becomes unreadable/unwritable & needs to be rebuilt (losing all data in the process).

The above is the story that I am getting from the administrators of an ECS cluster that my applications are using.

**Comment by jasoncwik** [comment]
In a _real_ ECS environment, losing one node out of four would not incur corruption and/or data loss.  However, in ECS CE, due to the smaller footprint, less disk space/redundancy, and the missing hardware management layer, it's possible that losing a node could cause the disruption described.  This is why we don't support the use of ECS CE in production environments.

**Comment by shanetreacy** [comment]
Thanks!!
