### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by adrianmo** [EMCECS/ECS-CommunityEdition#323]
I was going through the documentation and found the following broken links:

- https://github.com/EMCECS/ECS-CommunityEdition/blob/master/docs/source/installation/ECS-Installation.rst#L109
- https://github.com/EMCECS/ECS-CommunityEdition/blob/master/docs/source/installation/ECS-Installation.rst#L180
- https://github.com/EMCECS/ECS-CommunityEdition/blob/master/README.rst#L17

And one question from my ignorance, is there a reason why in `docs/source` we keep all pages both in Markdown and RST?

**Comment by captntuttle** [comment]
To answer your question about the markdown and rst, this is because we use sphinx to build the documentation and markdown to write it. We can switch to rst only but we've kept the markdown around to encourage documentation (as rst is kind of a pain to write). 

I convert the markdown to rst using pandoc. I will have a script that will take care of the conversion eventually, but I haven't gotten to it yet. 

It is possible to build the markdown but it doesn't work for us.
