### ISSUE TITLE
License needed ???

### ISSUE THREAD

**Issue by PierreLG04** [EMCECS/ECS-CommunityEdition#395]
### Expected Behavior
Hello,
I have installed the the Community Edition of ECS and after the Step1, I would like to configure it using the Web UI.
When I try to create a Storage Pool, I have an error message concerning licenses.
Where can I find the license.xml file ?

### Actual Behavior
(Please put additional output and logs in the section for that below)

### Steps to Reproduce Behavior

1. After Step1, start the Web UI
2. Manage Storage Pools and create 1

### Relevant Output and Logs
```
# Output and Logs go here
```

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by adrianmo** [comment]
Hi @PierreLG04,

The license is installed in Step 2. Please run Step 2 and let us know how it goes.

Thanks.

**Comment by PierreLG04** [comment]
Hi,
Thanks for your support.
Running the step2 solved the issue.
(Just one comment, if you logged in the Web interface after step1 and changed the password as requested), you cannot run step2 - error message concerning user and password).

Thanks again for your support.

**Comment by adrianmo** [comment]
@PierreLG04 you are welcome.

Right, if you change the password to something different than the one defined in the [`deploy.yml`](http://ecsce.readthedocs.io/en/latest/installation/deploy.yml.html) configuration file, then step2 will fail because the installer is not going to be able to log in and configure ECS.

Users should not access ECS before running Step 2 because ECS is still not configured and it's unusable at that time.

Thanks.
