### ISSUE TITLE
Install with CentOS - needs add. packages to be installed for step1 to run

### ISSUE THREAD

**Issue by eszych** [EMCECS/ECS-CommunityEdition#443]
### Expected Behavior

Installer should install all needed packages by default

### Actual Behavior
need to manually install the following packages to make "step1" run with no errors:
docker 
docker-python
ntp
pigz 

### Steps to Reproduce Behavior
1. fresh install of CentOS from "CentOS-7-x86_64-Everything-1804.iso" - minimal install selected as suggested
2. editing "deploy.yml" and running "./bootstrap.sh -y -g -c deploy.yml"
3. run 'step1' - error...
---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment]
Yes, this is something that has been an ongoing challenge with CentOS 7.4.  I always recommend using the more recent release of CentOS.  All testing is performed on the latest release anyway, so it's going to be the safest.  

The packages listed (with the exception of `docker-python`, which may be a new requirement for CentOS 7.4) are installed by `bootstrap.sh`.  This is curious.  @eszych could you perhaps email your `ECS-CommunityEdition/install.log` file to travis.wichert@emc.com so I can see what's happening with yum?

**Comment by padthaitofuhot** [comment]
@eszych I looked through the install log and see no indication that the packages mentioned in original post are failing to install, or in the case of `docker-python` are even required.  I am seeing this yum warning repeated in the log:
```
There are unfinished transactions remaining. You might consider running yum-complete-transaction, or "yum-complete-transaction --cleanup-only" and "yum history redo last", first to finish them. If those don't work you'll have to try removing/installing packages by hand (maybe package-cleanup can help).
```
Because this warning is present from the very beginning of the log, and because I have been unable to replicate this issue with my own CentOS 7.4 minimal images, it indicates to me that there is something broken in the image onto this which ECS CE is being deployed.

Do you continue to have this issue when using the most recent release of CentOS?
