### ISSUE TITLE
ECS Software 3.x - Troubles deploying/installing first time

### ISSUE THREAD

**Issue by Azimuts** [EMCECS/ECS-CommunityEdition#445]
I am trying to install ECS in a virtual machine under Windows. I want to mount it locally, just under this machine. Specifically, the version image is dellemc-ecsce-3.2.0.1-install-node-2.8.0-vm0.ova. I follow the steps described in point 1.2 of manual ecsce.pdf

1. videploy
  I  edit only  three entries (_as I said I want to do everything in one, in a single machine_ :)  : 

   - license_accepted: true
   - install_node: 127.0.0.1
   - storage_pools:
        name : sp1
        members : 
            - 192.168.43.10 ( obtained after doing an ifconfig ?)

![image](https://user-images.githubusercontent.com/42028117/43580667-8cad1124-9656-11e8-86c2-a9b81d1f9557.png)

2. step 1 : 

![image](https://user-images.githubusercontent.com/42028117/43580703-aa20eece-9656-11e8-9047-819020a09689.png)

3. step 2 : 
  Nothing.....

I have also tried island-step ( get the same issue but in island-step2

**I think I'm putting some of the ips wrong, and I do not know what to put. By putting everything to localhost 127.0.0.1, it also gives me problems (so i put the ifconfig returned ip ¿? ) .  ....Surely it is lack of knowledge. Thank you in advance for your attention.**
...

---
Notifies: @padthaitofuhot @captntuttle @adrianmo

**Comment by padthaitofuhot** [comment]
Hello @Azimuts , my apologies, but the file `ecsce.pdf` doesn't exist in this repo and I'm unsure about its contents or where you obtained it.  It is not canonical documentation.  

It seems to be misleading you to use the `localhost` IP address in many places instead of the virtual machine's primary IP address.  

It is also clear that the `ecs_block_devices:` data is incorrect; under VMWare, the device is usually named `/dev/sdb`, but you will need to check it with the Linux command `fdisk -l`.  

The PDF also seems to say nothing about ensuring that your DNS and NTP server IP addresses are correct.  DNS and NTP are required by ECS.  

After making the changes mentioned above, please attach your `deploy.yml` file to this issue and I'll check it for errors and ensure you have something that looks like it will work.

**Comment by padthaitofuhot** [comment]
Right, you'll need to use NTP and DNS servers that your VM can access.  If you are behind a corporate firewall, you may need to ask your IT department for assistance.

**Comment by padthaitofuhot** [comment]
16GB RAM for the VM is the minimum requirement.  There is not currently a work-around for this issue.
