### ISSUE TITLE
while installing ecs with ./bootstrap.sh -y -c deploy.yml getting ERROR: OS unknown and not supported: centos linux release 7.7.1908 (core)

### ISSUE THREAD

**Issue by Deepak8819** [EMCECS/ECS-CommunityEdition#485]
### Expected Behavior
>
>  ECS Community Edition Install Node Bootstrap 2.9.0r
>  ECS Software Image emccorp/ecs-software-3.2.2:3.2.2.0
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>
> Escalating privileges
>     You may be presented with the system sudo banner and asked
>     for your password depending on the Linux flavor and default
>     sudo configuration for your system.
>
>
> ERROR: OS unknown and not supported: centos linux release 7.7.1908 (core)

Kernel Version# uname -a
Linux 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Actual Behavior
(Please put additional output and logs in the section for that below)

### Steps to Reproduce Behavior

1.
2.
3.

### Relevant Output and Logs
```
# Output and Logs go here
```
> [ui/pull_image.sh] Cleaning up...
> Cleaning up...
> [ui/pull_image.sh]      [build tmp containers]
>      [build tmp containers]
sudo: docker: command not found
> [ui/pull_image.sh]      [ecs-install data containers]
>      [ecs-install data containers]
sudo: docker: command not found
> [ui/pull_image.sh]      [exited containers]
>      [exited containers]
sudo: docker: command not found
>      [dangling layers]
> [ui/pull_image.sh]      [dangling layers]
sudo: docker: command not found
> [ui/pull_image.sh] Pulling image emccorp/ecs-install:latest
> Pulling image emccorp/ecs-install:latest
sudo: docker: command not found
> [ui/pull_image.sh] ERROR: Failed to pull the installer image. Check the log for details.
> ERROR: Failed to pull the installer image. Check the log for details.
> [./bootstrap.sh] ERROR: We couldn't pull the ecs-install image for some reason. Please check the logs.
> [./bootstrap.sh] ERROR: If it's something simple, such as the ecs-install:latest image missing from
> [./bootstrap.sh] ERROR: your custom Docker registry, or if your Internet access isn't working, then
> [./bootstrap.sh] ERROR: you may be able to solve the problem by first solving one of the above issues.
> [./bootstrap.sh] ERROR: If you still need more help after trying the above, you can reach us on GitHub.
> [./bootstrap.sh]
> [./bootstrap.sh]  ECS Community Edition Install Node Bootstrap 2.9.1r
> [./bootstrap.sh]  ECS Software Image emccorp/ecs-software-3.3.0:3.3.0.0
> [./bootstrap.sh] ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> [./bootstrap.sh]
> [./bootstrap.sh] Escalating privileges
---
Notifies: @captntuttle

**Comment by captntuttle** [comment]
I will have to update for CentOS 7.7 - stay tuned

**Comment by kedmon** [comment]
Is the 7.7 issue just with the bootstrap process?  Would installing from OVA work with 7.7 currently?

**Comment by captntuttle** [comment]
@kedmon yes, good point - the OVA should work.

**Comment by kedmon** [comment]
Because I'm blocked on trying to install via OVA, I tried to see if I could get the boostrap install to work on 7.7 by just copying centos76.plugin.sh to centos77.plugin.sh and detecting that in the bootstrap process.

With that, the bootstrap *appeared* to work.  However, after rebooting the VM, I could not find the step1 or step2 commands to run.  Should those be created by the bootstrap process?

I did find the following from install.log, which certainly looks suspicious.  Any suggestion what the failure point is?

++++++++++++++++++++++++++++++++++++++
Dependency Installed:
libpcap.x86_64 14:1.5.3-11.el7
oniguruma.x86_64 0:5.9.5-3.el7
python-docker-pycreds.noarch 1:0.3.0-9.el7_6
python-websocket-client.noarch 0:0.56.0-3.git3c25814.el7

Complete!
curl: (35) TCP connection reset by peer

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
> [./bootstrap.sh] Installing virtual machine guest additions
++++++++++++++++++++++++++++++++++++++

**Comment by kedmon** [comment]
Actually, I suspect the issue above is that I'm in a locked-down environment that does not have unrestricted internet access.  So whatever it is trying to access with curl is probably not available.

**Comment by captntuttle** [comment]
@kedmon is this still an issue for you?
