### ISSUE TITLE
Failed Install

### ISSUE THREAD

**Issue by dewybc** [EMCECS/ECS-CommunityEdition#5]
When running the first install script, it is unable to pull the "latest" image from emccorp/ecs-software.  See screen shot below.  The install says if finished but the gui is not available and docker ps shows nothing.

![screen shot 2015-08-04 at 9 28 24 am](https://cloud.githubusercontent.com/assets/13643395/9061707/853879c6-3a8b-11e5-8474-c204478b2138.png)

**Comment by thakkd** [comment]
That is likely because you could not reach the docker hub due to network restrictions in your environment. You can verify this by trying docker pull ubuntu and if it fails with a similar message as the error in the Step 1 Script. As a workaround you can try is to install the docker manually and also add the docker image out of band. Some folks on the EMC CORP network have reported they were able to get around the network issue by using some certificates but YMMV depending on your environment.

**Comment by msalem2** [comment]
Please get latest version from github. It continues new updated image name

Sent from my iPhone

On Aug 4, 2015, at 7:03 AM, thakkd <notifications@github.com<mailto:notifications@github.com>> wrote:


That is likely because you could not reach the docker hub due to network restrictions in your environment. You can verify this by trying docker pull ubuntu and if it fails with a similar message as the error in the Step 1 Script. As a workaround you can try is to install the docker manually and also add the docker image out of band. Some folks on the EMC CORP network have reported they were able to get around the network issue by using some certificates but YMMV depending on your environment.
