### ISSUE TITLE
ECS-3.4.0.0 deployment stuck on " WAIT: API service is not alive. This is likely temporary."

### ISSUE THREAD

**Issue by sahmed1501** [EMCECS/ECS-CommunityEdition#512]
### Expected Behavior
I understand that this message is expected and repeated for a few times. I even left it running for the whole night.

### Actual Behavior
(Please put additional output and logs in the section for that below)

TASK [common_deploy : Common | Increase memory for sr] **************************************************************************************************************************************
ok: [192.168.1.197]

TASK [common_deploy : Common | Merge configurations into configuration data container] ******************************************************************************************************
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)
changed: [192.168.1.197] => (item=/opt/storageos/conf/ssm.object.properties)

TASK [common_deploy : Common | Create the ECS StorageOS container] **************************************************************************************************************************
changed: [192.168.1.197]

PLAY [Installer | Slice nodes into OS groups for init scripts] ******************************************************************************************************************************

TASK [group_by] *****************************************************************************************************************************************************************************
ok: [192.168.1.197]

PLAY [CentOS 7 | Install init scripts] ******************************************************************************************************************************************************

TASK [CentOS_7_service_policies : CentOS 7 | Insert ecs.service into systemd] ***************************************************************************************************************
changed: [192.168.1.197]

PLAY RECAP **********************************************************************************************************************************************************************************
192.168.1.197              : ok=42   changed=33   unreachable=0    failed=0

Playbook run took 0 days, 0 hours, 0 minutes, 51 seconds

PLAY [Common | Ping data nodes before doing anything else] **********************************************************************************************************************************

TASK [ping] *********************************************************************************************************************************************************************************
ok: [192.168.1.197]

PLAY [Common | Start and enable ECS services] ***********************************************************************************************************************************************

TASK [common_start_enable_service : Common | Enable ECS service and start ECS] **************************************************************************************************************
changed: [192.168.1.197]

PLAY RECAP **********************************************************************************************************************************************************************************
192.168.1.197              : ok=2    changed=1    unreachable=0    failed=0

Playbook run took 0 days, 0 hours, 0 minutes, 2 seconds

[admin@localhost ~]$ ova-step2
> Pinging Management API Endpoint until ready
> Pinging endpoint 192.168.1.197... (CTRL-C to break)
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.
> WAIT: API service is not alive. This is likely temporary.

### Steps to Reproduce Behavior

1. videploy (add IP address, dns, ntp and /dev/sdb). It is all successful. No error.
2. ova-step1  # it is all successful. No error
3. ova-step2 # it is STUCK on WAIT: API service is not alive. This is likely temporary.

### Relevant Output and Logs

I am not sure what logs to gather and put it here.

---
Notifies: @captntuttle

**Comment by sahmed1501** [comment]
[admin@localhost log]$ sudo docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                         PORTS               NAMES
cd1eaa22e1be        emccorp/ecs-install:latest    "/usr/local/bin/entr…"   About an hour ago   Up About an hour                                   wizardly_cartwright
21003da4433c        emccorp/ecs-software:latest   "/opt/vipr/boot/boot…"   About an hour ago   Up About an hour                                   ecs-storageos
b7cc7c802597        emccorp/ecs-software:latest   "/bin/echo 'ECS conf…"   About an hour ago   Created                                            ecs-config
f55a7f7ee352        emccorp/ecs-install:latest    "/bin/echo echo 'Dat…"   About an hour ago   Exited (0) About an hour ago                       ecs-install-data

**Comment by agregory999** [comment]
I'm at the same point as well.  Step2 hangs forever and thus never installs the license, which is required in order to proceed.  So my issue is basically the same as yours.  I am running 3.4 on GCP/Centos7.  I gave it plenty of resources.

**Comment by jorge-alg** [comment]
I got the same issue, but I noticed that when I change the ip address in the nmtui I didn't change the mode from Automatic to Manual after I change that it works fine.

You have two IP address the DHCP and static you can verify that with the command "nmcli".

**Comment by laszlo-laszlo** [comment]
Hello,
I've a same almost same issue.
videploy: fine
ova-step1: fine
ova-step2: failed

`[admin@ecs1 ~]$ ova-step2
> Pinging Management API Endpoint until ready
> Pinging endpoint 172.22.142.25... (CTRL-C to break)
> PONG: api_endpoint=172.22.142.25 username=root diag_endpoint=172.22.142.25 dt_total=160 dt_unready=0 dt_unknown=0

> Installing licensing in ECS VDC(s)
> Using default license
> Adding licensing to VDC: vdc1
>       OK
> Added default license to ECS

> Pinging Management API Endpoint until ready
> Pinging endpoint 172.22.142.25... (CTRL-C to break)
> PONG: api_endpoint=172.22.142.25 username=root diag_endpoint=172.22.142.25 dt_total=160 dt_unready=0 dt_unknown=0

> Creating Storage Pool: vdc1/sp1
Traceback (most recent call last):
  File "/usr/bin/ecsconfig", line 11, in <module>
    load_entry_point('ecsdeploy==2.9.1.post0', 'console_scripts', 'ecsconfig')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1163, in invoke
    rv.append(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/bin/ecsconfig.py", line 661, in sp
    tasks = add_all()
  File "/usr/bin/ecsconfig.py", line 637, in add_all
    sp_tasks.extend(add_one(name))
  File "/usr/bin/ecsconfig.py", line 617, in add_one
    sp_id = sp_create(name, conf.ecs.sp_ecs_options(name))
  File "/usr/bin/ecsconfig.py", line 575, in sp_create
    resp = conf.api_client.storage_pool.create(**kwargs)
  File "/usr/lib/python2.7/site-packages/ecsclient/common/provisioning/storage_pool.py", line 109, in create
    return self.conn.post('vdc/data-services/varrays', json_payload=payload)
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 120, in post
    return self._request(url, json_payload, http_verb='POST')
  File "/usr/lib/python2.7/site-packages/ecsclient/baseclient.py", line 170, in _request
    raise ECSClientException.from_response(req)
ecsclient.common.exceptions.ECSClientException: Operation cannot be performed due to entered varray sp1 conflicts with existing sp1 - Bad request body: https://172.22.142.25:4443/vdc/data-services/varrays 400 Bad Request  [first 60 chars of response] {"code":1013,"retryable":false,"description":"Bad request bo`

Endpoint seems running:
`[admin@ecs1 ~]$ sudo ss -tulipan|grep LISTEN | grep 4443
tcp    LISTEN     0      128    127.0.0.1:4443                  *:*                   users:(("nginx",pid=26755,fd=9),("nginx",pid=26754,fd=9),("nginx",pid=26753,fd=9))
tcp    LISTEN     0      128    172.22.142.25:4443                  *:*                   users:(("nginx",pid=26755,fd=8),("nginx",pid=26754,fd=8),("nginx",pid=26753,fd=8))
tcp    LISTEN     0      50       [::ffff:127.0.0.1]:64443              [::]:*                   users:(("java",pid=23735,fd=343))
`
Please give advice to correct this issue. Thank you!

**Comment by jorge-alg** [comment]
Hello @laszlo-laszlo.

Verify the deploy file if you added all the nodes. Between ova-step1 and ova-step2 you need to wait almost 10 minutes because all the ECS TCP/UDP ports must be opened, and then you can do the ova-step2.

You can use the following command "ss -ltn4" or just type the ip of the node in your browser and wait until the login screen of the ECS appears.

**Comment by padthaitofuhot** [comment]
Closing due to age.
