### ISSUE TITLE
Can't Login Using root/ChangeMe

### ISSUE THREAD

**Issue by amarcionek** [EMCECS/ECS-CommunityEdition#8]
Failure to login to the admin gui using root/ChangeMe.  This also manifests itself when attempting to run the script:

`Executing getAuthToken: curl -i -k https://192.168.21.54:4443/login -u root:ChangeMe`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   373  100   373    0     0   4576      0 --:--:-- --:--:-- --:--:--  4604`

`Traceback (most recent call last):
  File "step2_object_provisioning.py", line 298, in <module>
    main(sys.argv[1:])
  File "step2_object_provisioning.py", line 220, in main
    AuthToken=getAuthToken(ECSNode, "root", "ChangeMe")
  File "step2_object_provisioning.py", line 17, in getAuthToken
    assert searchObject, "Get Auth Token failed"
AssertionError: Get Auth Token failed`

**Comment by rodfmarin** [comment]
This happened to me if the cluster wasn't completely online.

**Comment by jasoncwik** [comment]
Yes, we've seen this if you don't wait long enough between step 1 and step 2.  We are fixing the step 1 script so it does not exit until the auth service is online.

**Comment by padthaitofuhot** [comment]
@amarcionek Can you try the latest master and see if this is still an issue on a VM with ~64GB RAM?  Thank you!

**Comment by amarcionek** [comment]
I will see what I can do. I might not have the cycles for about a week.

**Comment by jasoncwik** [comment]
I think I've RCA'd this issue.  The long login time is caused by failure to insert audit records to track the login.  Tracing the call through provisionsvc and eventsvc, I saw that the problem was that the EV table was read-only because it couldn't create journal records.  This was caused because SSM wasn't allocating blocks.  SSM wasn't allocating blocks because the low watermark on the L2 table was causing excessive borrowing from L1, leaving L1 with no blocks to allocate.  PR #62 adjusts ssm settings for smaller storage systems.  We will make this setting permanent in a future ECS CE image since modifying ssm.object.properties will not persist across container restart.

**Comment by jasoncwik** [comment]
Sorry, I mean fix is in PR #63
